### ISSUE TITLE
Consider Open Source License

### ISSUE THREAD

**Issue by madnight** [andris9/imap-api#1]
Please consider a open source license e. g. MIT.

**Comment by andris9** [comment]
TBD.

I had to create a completely new IMAP client module for this project and this module does not have a license assigned yet either: https://imapflow.com/

**Comment by andris9** [comment]
IMAP API is now officially open source as it is licensed under GNU Affero General Public License v3.0 or later

**Comment by nisanth074** [comment]
@andris9 Can I use imapapi in a commercial closed source application under this license?

> IMAP API is now officially open source as it is licensed under GNU Affero General Public License v3.0 or later

**Comment by jhult** [comment]
In regards to usage and the AGPLv3, I figured I would leave this info here for other readers:

- https://opensource.stackexchange.com/a/5004/405
- https://medium.com/swlh/understanding-the-agpl-the-most-misunderstood-license-86fd1fe91275
