### ISSUE TITLE
submit a simple email make 500 error

### ISSUE THREAD

**Issue by DonsWayo** [andris9/imap-api#6]
**Describe the bug**
on swagger ui, submit a new email with basic things returns a 500

**To Reproduce**
{
  
  "from": 
    {
      "name": "From Me",
      "address": "example@example.com"
    }
  ,
  "to": [
    {
      "address": "example@gmail.com"
    }
  ],

  "subject": "What a wonderful message",
  "text": "Hello from myself!"
}

**Expected behavior**
Send a mail 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser  chrome
 - Version master

**Additional context**
Maybe a bug,the from on swagger appear as array and I think need to be a object (as api respone say)

**Comment by andris9** [comment]
Could you try the same from command line:

```
curl -XPOST "localhost:3000/v1/account/ACCOUNT_ID/submit" -H "content-type: application/json" -d '{
  
  "from": {
      "name": "From Me",
      "address": "example@example.com"
    },
  "to": [
    {
      "address": "andris.reinman@gmail.com"
    }
  ],
  "subject": "What a wonderful message",
  "text": "Hello from myself!"
}'
```

In the same time check the server logs. There should be a better error description saying what is going on. For example if the from address is invalid etc (example.com can not send mail)

**Comment by DonsWayo** [comment]
this is the error part of the log:

`"err":{"type":"Error","message":"123145516175360:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n","stack":"Error: 123145516175360:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n","library":"SSL routines","function":"ssl3_get_record","reason":"wrong version number","code":"ESOCKET","command":"CONN"},"v":1}`

maybe need something more?, thanks for the quick reply :)

**Comment by andris9** [comment]
Seems like the SMTP configuration is off. For example did you use secure:true for port other than 465? You can try different configuration settings with the `/v1/verifyAccount` endpoint. If it gives you an error then you can not use that config.

**Comment by DonsWayo** [comment]
yes, I use secure true with the port 587, was a mistake, now change as work perfect!

thanks for the help.
